version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - S3_BUCKET=FILL IN
        - S3_ACCESS_KEY=FILL IN
        - S3_SECRET_ACCESS_KEY=FILL IN
        - REDIS_ENDPOINT='redis://redis:6379/0'
    container_name: flask_app
    command: gunicorn -b 0.0.0.0:5001 app:flask_app
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    depends_on:
      - redis

  celery_worker:
    build: 
      context: .
      args:
        - S3_BUCKET=FILL IN
        - S3_ACCESS_KEY=FILL IN
        - S3_SECRET_ACCESS_KEY=FILL IN
        - REDIS_ENDPOINT='redis://redis:6379/0'
    container_name: celery_worker
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:7.4-alpine"
    container_name: redis
    ports:
      - "6379:6379"
